// Generated by the Supabase CLI — do not edit by hand.
//
//   supabase gen types typescript --project-id gmvrkzumvwhrkqzqwcnu \
//     --schema public --schema health > src/lib/supabase/database.types.ts
//
// Re-run this after any migration that changes a table, column or function
// signature. It is what makes the clinical queries in src/lib/health/client.ts
// compile-checked against the real schema instead of cast to shape.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  health: {
    Tables: {
      access_log: {
        Row: {
          action: string
          actor_role: string
          actor_user_id: string | null
          at: string
          id: number
          ip: unknown
          patient_id: string | null
          resource: string | null
          resource_id: string | null
          user_agent: string | null
        }
        Insert: {
          action: string
          actor_role: string
          actor_user_id?: string | null
          at?: string
          id?: number
          ip?: unknown
          patient_id?: string | null
          resource?: string | null
          resource_id?: string | null
          user_agent?: string | null
        }
        Update: {
          action?: string
          actor_role?: string
          actor_user_id?: string | null
          at?: string
          id?: number
          ip?: unknown
          patient_id?: string | null
          resource?: string | null
          resource_id?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      consents: {
        Row: {
          delete_after: string | null
          granted_at: string
          id: string
          notice_version: string
          patient_id: string
          scope: Json
          superseded_at: string | null
          withdrawn_at: string | null
        }
        Insert: {
          delete_after?: string | null
          granted_at?: string
          id?: string
          notice_version: string
          patient_id: string
          scope: Json
          superseded_at?: string | null
          withdrawn_at?: string | null
        }
        Update: {
          delete_after?: string | null
          granted_at?: string
          id?: string
          notice_version?: string
          patient_id?: string
          scope?: Json
          superseded_at?: string | null
          withdrawn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "consents_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      exercise_sessions: {
        Row: {
          activity: string
          created_at: string
          id: string
          intensity: string | null
          minutes: number
          note: string | null
          patient_id: string
          recorded_at: string
        }
        Insert: {
          activity: string
          created_at?: string
          id?: string
          intensity?: string | null
          minutes: number
          note?: string | null
          patient_id: string
          recorded_at: string
        }
        Update: {
          activity?: string
          created_at?: string
          id?: string
          intensity?: string | null
          minutes?: number
          note?: string | null
          patient_id?: string
          recorded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exercise_sessions_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      exercise_sessions_archive: {
        Row: {
          activity: string
          archived_at: string
          created_at: string
          id: string
          intensity: string | null
          minutes: number
          note: string | null
          patient_id: string
          recorded_at: string
        }
        Insert: {
          activity: string
          archived_at?: string
          created_at?: string
          id?: string
          intensity?: string | null
          minutes: number
          note?: string | null
          patient_id: string
          recorded_at: string
        }
        Update: {
          activity?: string
          archived_at?: string
          created_at?: string
          id?: string
          intensity?: string | null
          minutes?: number
          note?: string | null
          patient_id?: string
          recorded_at?: string
        }
        Relationships: []
      }
      patients: {
        Row: {
          created_at: string
          patient_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          patient_id?: string
          user_id: string
        }
        Update: {
          created_at?: string
          patient_id?: string
          user_id?: string
        }
        Relationships: []
      }
      profile_entries: {
        Row: {
          category: string
          created_at: string
          detail: string | null
          id: string
          is_current: boolean
          label: string
          occurred_on: string | null
          patient_id: string
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          detail?: string | null
          id?: string
          is_current?: boolean
          label: string
          occurred_on?: string | null
          patient_id: string
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          detail?: string | null
          id?: string
          is_current?: boolean
          label?: string
          occurred_on?: string | null
          patient_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_entries_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      readings: {
        Row: {
          chol_hdl_mgdl: number | null
          chol_ldl_mgdl: number | null
          chol_total_mgdl: number | null
          chol_trig_mgdl: number | null
          created_at: string
          diastolic: number | null
          entered_unit: string | null
          glucose_context: string | null
          glucose_mgdl: number | null
          id: string
          kind: string
          note: string | null
          patient_id: string
          pulse: number | null
          recorded_at: string
          systolic: number | null
        }
        Insert: {
          chol_hdl_mgdl?: number | null
          chol_ldl_mgdl?: number | null
          chol_total_mgdl?: number | null
          chol_trig_mgdl?: number | null
          created_at?: string
          diastolic?: number | null
          entered_unit?: string | null
          glucose_context?: string | null
          glucose_mgdl?: number | null
          id?: string
          kind: string
          note?: string | null
          patient_id: string
          pulse?: number | null
          recorded_at: string
          systolic?: number | null
        }
        Update: {
          chol_hdl_mgdl?: number | null
          chol_ldl_mgdl?: number | null
          chol_total_mgdl?: number | null
          chol_trig_mgdl?: number | null
          created_at?: string
          diastolic?: number | null
          entered_unit?: string | null
          glucose_context?: string | null
          glucose_mgdl?: number | null
          id?: string
          kind?: string
          note?: string | null
          patient_id?: string
          pulse?: number | null
          recorded_at?: string
          systolic?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "readings_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      readings_archive: {
        Row: {
          archived_at: string
          chol_hdl_mgdl: number | null
          chol_ldl_mgdl: number | null
          chol_total_mgdl: number | null
          chol_trig_mgdl: number | null
          created_at: string
          diastolic: number | null
          entered_unit: string | null
          glucose_context: string | null
          glucose_mgdl: number | null
          id: string
          kind: string
          note: string | null
          patient_id: string
          pulse: number | null
          recorded_at: string
          systolic: number | null
        }
        Insert: {
          archived_at?: string
          chol_hdl_mgdl?: number | null
          chol_ldl_mgdl?: number | null
          chol_total_mgdl?: number | null
          chol_trig_mgdl?: number | null
          created_at?: string
          diastolic?: number | null
          entered_unit?: string | null
          glucose_context?: string | null
          glucose_mgdl?: number | null
          id?: string
          kind: string
          note?: string | null
          patient_id: string
          pulse?: number | null
          recorded_at: string
          systolic?: number | null
        }
        Update: {
          archived_at?: string
          chol_hdl_mgdl?: number | null
          chol_ldl_mgdl?: number | null
          chol_total_mgdl?: number | null
          chol_trig_mgdl?: number | null
          created_at?: string
          diastolic?: number | null
          entered_unit?: string | null
          glucose_context?: string | null
          glucose_mgdl?: number | null
          id?: string
          kind?: string
          note?: string | null
          patient_id?: string
          pulse?: number | null
          recorded_at?: string
          systolic?: number | null
        }
        Relationships: []
      }
      settings: {
        Row: {
          cholesterol_unit: string
          glucose_unit: string
          patient_id: string
          updated_at: string
          water_goal_ml: number
        }
        Insert: {
          cholesterol_unit?: string
          glucose_unit?: string
          patient_id: string
          updated_at?: string
          water_goal_ml?: number
        }
        Update: {
          cholesterol_unit?: string
          glucose_unit?: string
          patient_id?: string
          updated_at?: string
          water_goal_ml?: number
        }
        Relationships: [
          {
            foreignKeyName: "settings_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: true
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      water_intake: {
        Row: {
          created_at: string
          id: string
          ml: number
          patient_id: string
          recorded_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          ml: number
          patient_id: string
          recorded_at: string
        }
        Update: {
          created_at?: string
          id?: string
          ml?: number
          patient_id?: string
          recorded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "water_intake_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["patient_id"]
          },
        ]
      }
      water_intake_archive: {
        Row: {
          archived_at: string
          created_at: string
          id: string
          ml: number
          patient_id: string
          recorded_at: string
        }
        Insert: {
          archived_at?: string
          created_at?: string
          id?: string
          ml: number
          patient_id: string
          recorded_at: string
        }
        Update: {
          archived_at?: string
          created_at?: string
          id?: string
          ml?: number
          patient_id?: string
          recorded_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      archive_old: { Args: never; Returns: number }
      current_patient_id: { Args: never; Returns: string }
      delete_my_health_data: { Args: never; Returns: undefined }
      grant_consent: {
        Args: { notice_version: string; scope: Json }
        Returns: string
      }
      has_active_consent: { Args: { pid: string }; Returns: boolean }
      log_app_open: { Args: never; Returns: undefined }
      log_export: { Args: never; Returns: undefined }
      my_status: { Args: never; Returns: Json }
      purge_patient: { Args: { pid: string }; Returns: undefined }
      purge_withdrawn: { Args: never; Returns: number }
      request_ip: { Args: never; Returns: unknown }
      request_user_agent: { Args: never; Returns: string }
      withdraw_consent: { Args: never; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      account_consents: {
        Row: {
          captured_at: string
          id: string
          notice_version: string
          scope: Json
          user_id: string
        }
        Insert: {
          captured_at?: string
          id?: string
          notice_version: string
          scope: Json
          user_id: string
        }
        Update: {
          captured_at?: string
          id?: string
          notice_version?: string
          scope?: Json
          user_id?: string
        }
        Relationships: []
      }
      aurora_bookings: {
        Row: {
          appointment_date: string
          consent_notice_version: string
          consented_at: string
          created_at: string
          date_of_birth: string
          email: string | null
          full_name: string
          id: string
          location: string
          phone: string
          reason: string | null
          reference: string
          reminders_opt_in: boolean
          service: string
          status: string
          time_window: string
          user_id: string | null
        }
        Insert: {
          appointment_date: string
          consent_notice_version: string
          consented_at: string
          created_at?: string
          date_of_birth: string
          email?: string | null
          full_name: string
          id?: string
          location: string
          phone: string
          reason?: string | null
          reference: string
          reminders_opt_in?: boolean
          service: string
          status?: string
          time_window: string
          user_id?: string | null
        }
        Update: {
          appointment_date?: string
          consent_notice_version?: string
          consented_at?: string
          created_at?: string
          date_of_birth?: string
          email?: string | null
          full_name?: string
          id?: string
          location?: string
          phone?: string
          reason?: string | null
          reference?: string
          reminders_opt_in?: boolean
          service?: string
          status?: string
          time_window?: string
          user_id?: string | null
        }
        Relationships: []
      }
      aurora_contacts: {
        Row: {
          consent_notice_version: string
          consented_at: string
          created_at: string
          email: string
          full_name: string
          id: string
          kind: string
          message: string
          organisation: string | null
          reference: string
          status: string
        }
        Insert: {
          consent_notice_version: string
          consented_at: string
          created_at?: string
          email: string
          full_name: string
          id?: string
          kind: string
          message: string
          organisation?: string | null
          reference: string
          status?: string
        }
        Update: {
          consent_notice_version?: string
          consented_at?: string
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          kind?: string
          message?: string
          organisation?: string | null
          reference?: string
          status?: string
        }
        Relationships: []
      }
      aurora_home_visits: {
        Row: {
          address: string
          area: string
          consent_notice_version: string
          consented_at: string
          created_at: string
          full_name: string
          id: string
          mobility_note: string | null
          phone: string
          reference: string
          service: string
          status: string
          time_window: string
          visit_date: string
        }
        Insert: {
          address: string
          area: string
          consent_notice_version: string
          consented_at: string
          created_at?: string
          full_name: string
          id?: string
          mobility_note?: string | null
          phone: string
          reference: string
          service: string
          status?: string
          time_window: string
          visit_date: string
        }
        Update: {
          address?: string
          area?: string
          consent_notice_version?: string
          consented_at?: string
          created_at?: string
          full_name?: string
          id?: string
          mobility_note?: string | null
          phone?: string
          reference?: string
          service?: string
          status?: string
          time_window?: string
          visit_date?: string
        }
        Relationships: []
      }
      aurora_rights_requests: {
        Row: {
          closed_at: string | null
          details: string | null
          due_by: string
          email: string
          full_name: string
          id: string
          opened_at: string
          reference: string
          requested_right: string
          status: string
        }
        Insert: {
          closed_at?: string | null
          details?: string | null
          due_by: string
          email: string
          full_name: string
          id?: string
          opened_at?: string
          reference: string
          requested_right: string
          status?: string
        }
        Update: {
          closed_at?: string | null
          details?: string | null
          due_by?: string
          email?: string
          full_name?: string
          id?: string
          opened_at?: string
          reference?: string
          requested_right?: string
          status?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          dob: string | null
          full_name: string | null
          id: string
          marketing_opt_in: boolean
          phone: string | null
          role: string
        }
        Insert: {
          created_at?: string
          dob?: string | null
          full_name?: string | null
          id: string
          marketing_opt_in?: boolean
          phone?: string | null
          role?: string
        }
        Update: {
          created_at?: string
          dob?: string | null
          full_name?: string | null
          id?: string
          marketing_opt_in?: boolean
          phone?: string | null
          role?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  health: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
